BookUI/Models/ApiRequest.cs
using static BookUI.StaticDetails;

namespace BookUI.Models
{
    public class ApiRequest
    {
        public ApiType Apitype { get; set; }
        public string Url { get; set; }
        public object Data { get; set; }
        public string AccessToken { get; set; }
    }
}

BookUI/Models/ApiResponse.cs
using System.Net;

namespace BookUI.Models
{
    public class ApiResponse
    {
        public bool IsSuccess { get; set; } = true;
        public object Data { get; set; }
        public string StatusMessage { get; set; } = "";
        public List<string> ErrorMessages { get; set; }
    }
}

BookUI/Models/ErrorViewModel.cs
namespace BookUI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BookUI/Controllers/BookController.cs
using Azure;
using BookUI.Models;
using BookUI.Services;
using Labb1_Minimal_API.Models;
using Labb1_Minimal_API.Models.DTOs;
using Labb1_Minimal_API.Services;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using static System.Reflection.Metadata.BlobBuilder;

namespace BookUI.Controllers
{
    public class BookController : Controller
    {
        //public ApiResponse Respons { get; set; }
        public IBookService BookService { get; set; }
        public BookController(IBookService service)
        {
            this.BookService = service;
            //this.Respons = new ApiResponse();
        }
 
        public async Task<IActionResult> BookIndex()
        {
            List<BookDTO> list = new List<BookDTO>();
            var result = await BookService.GetAllAsync<APIResponse>();
            if(result != null && result.IsSuccess)
            {
                // Making sure we are getting the right data in, and 
                // making it into a list of bookDTO
                list = JsonConvert.DeserializeObject<List<BookDTO>>
                    (Convert.ToString(result.Result));
            }

            return View(list);
        }

        [HttpGet]
        public async Task<IActionResult> NewBook()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> NewBook(BookCreateDTO newBook)
        {

            await Console.Out.WriteLineAsync("Genre = " + newBook.Genre);
            await Console.Out.WriteLineAsync("Title = " + newBook.Title);
            await Console.Out.WriteLineAsync("IsAvalible = " + newBook.IsAvalible);

            var response = await BookService.NewBookAsync<APIResponse>(newBook);

            if(response != null && response.IsSuccess)
            {
                return RedirectToAction(nameof(BookIndex));
            }
            else
            {
                return RedirectToAction("BookErrors", response);
            }

        }

        public async Task<IActionResult> BookErrors(APIResponse response)
        {
            return View(response);
        }

        public async Task<IActionResult> BookInfo(int id)
        {
            var result = await BookService.GetByIdAsync<APIResponse>(id);
            if(result != null && result.IsSuccess)
            {
                BookDTO book = JsonConvert.DeserializeObject<BookDTO>(Convert.ToString(result.Result));
                return View(book);
            }
            return NotFound();
        }

        [HttpGet]
        public async Task<IActionResult> UpdateBook(int id)
        {
            var response = await BookService.GetByIdAsync<APIResponse>(id);
            if (response != null && response.IsSuccess)
            {
                BookDTO book = JsonConvert.DeserializeObject<BookDTO>(Convert.ToString(response.Result));
                return View(book);
            }
            return BadRequest();
        }

        [HttpPost]
        public async Task<IActionResult> UpdateBook(BookUpdateDTO newBook)
        {
            var response = await BookService.UpdateBookAsync<APIResponse>(newBook);
            if (response != null && response.IsSuccess)
            {
                return RedirectToAction(nameof(BookIndex));
            }
            else
            {
                return RedirectToAction("BookErrors", response);
            }
        }

        public async Task<IActionResult> DeleteBook(int id)
        {
            await BookService.DeleteBookAsync<APIResponse>(id);

            return RedirectToAction(nameof(BookIndex));
        }

        //[Route("/api/book/{content}")]
        public async Task<IActionResult> BookSearch(string content)
        {
            var response = await BookService.SearchBookAsync<APIResponse>(content);

            if(String.IsNullOrEmpty(content))
            {
                RedirectToAction(nameof(BookErrors));
            }

            if(response.IsSuccess)
            {
                var books = JsonConvert.DeserializeObject<IEnumerable<BookDTO>>(Convert.ToString(response.Result));
                await Console.Out.WriteLineAsync(books.ToString());
                return View("BookIndex", books);
            }

            return RedirectToAction(nameof(BookErrors), response);
        }
    }
}

BookUI/Controllers/HomeController.cs
using BookUI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BookUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BookUI/Views/Book/BookErrors.cshtml
@model APIResponse

<h1 class="text-danger">Errors Accoured!</h1>
<br />

<ul class="list-group">
@foreach (var item in Model.ErrorMessages)
{

  <li class="list-group-item">@item</li>

}
</ul>

<br />
<a asp-action="BookIndex" class="btn btn-info">Back</a>

BookUI/Views/Book/BookIndex.cshtml
@model IEnumerable<BookDTO>


<h1>All Books</h1>

<a asp-action="NewBook" class="btn btn-primary">New Book</a>
<br />
<Form asp-action="BookSearch" method="post">
    <Input name="content" class="form-control-sm mt-2" type="search" placeholder="Search" aria-label="Search">
    <button type="submit" class="btn-xs border-2 btn-outline-success bg-info"><i class="fa-solid fa-magnifying-glass"></i></button>
</Form>

<hr />
<table class="table">
    <thead class="table-dark">
        <tr>
            <th>@Html.DisplayNameFor(model => model.Title)</th>
            <th>@Html.DisplayNameFor(model => model.Author)</th>
            <th>@Html.DisplayNameFor(model => model.Genre)</th>
            <th>@Html.DisplayNameFor(model => model.IsAvalible)</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(itemModel => item.Title)</td>
                <td>@Html.DisplayFor(itemModel => item.Author)</td>
                <td>@Html.DisplayFor(itemModel => item.Genre)</td>
                <td>@Html.DisplayFor(itemModel => item.IsAvalible)</td>
                <td>
                    <a asp-action="BookInfo" asp-route-ID="@item.Id" class="btn btn-info">Info</a>
                    <a asp-action="UpdateBook" asp-route-ID="@item.Id" class="btn btn-warning">Edit</a>
                    <a asp-action="DeleteBook" asp-route-ID="@item.Id" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

BookUI/Views/Book/BookInfo.cshtml
@model BookDTO

<div class="card" style="width: 18rem;">
    <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
        <h5 class="card-title">@Html.DisplayFor(model => model.Title)</h5>
        <p class="card-text">@Html.DisplayFor(model => model.Description)</p>
  </div>
</div>
<br />
<a asp-action="BookIndex" class="btn btn-info">Back</a>

BookUI/Views/Book/BookSearch.cshtml
@model IEnumerable<BookDTO>


<h1>All Books</h1>

<a asp-action="NewBook" class="btn btn-primary">New Book</a>
<br />
<Form asp-action="Search" method="post">
    <Input name="content" class="form-control-sm mt-2" type="search" placeholder="Search" aria-label="Search">
    <button type="submit" class="btn-xs border-2 btn-outline-success bg-info"><i class="fa-solid fa-magnifying-glass"></i></button>
</Form>

<hr />
<table class="table">
    <thead class="table-dark">
        <tr>
            <th>@Html.DisplayNameFor(model => model.Title)</th>
            <th>@Html.DisplayNameFor(model => model.Author)</th>
            <th>@Html.DisplayNameFor(model => model.Genre)</th>
            <th>@Html.DisplayNameFor(model => model.IsAvalible)</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(itemModel => item.Title)</td>
                <td>@Html.DisplayFor(itemModel => item.Author)</td>
                <td>@Html.DisplayFor(itemModel => item.Genre)</td>
                <td>@Html.DisplayFor(itemModel => item.IsAvalible)</td>
                <td>
                    <a asp-action="BookInfo" asp-route-ID="@item.Id" class="btn btn-info">Info</a>
                    <a asp-action="UpdateBook" asp-route-ID="@item.Id" class="btn btn-warning">Edit</a>
                    <a asp-action="DeleteBook" asp-route-ID="@item.Id" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

BookUI/Views/Book/NewBook.cshtml
@model BookCreateDTO

<h1>Create New Book</h1>
<form asp-action="NewBook">
   @*  <div asp-validation-summary="ModelOnly" class="text-danger"></div> *@
  <div class="mb-3">
        <label asp-for="Title" class="form-label"><b>Title</b></label>
        <input asp-for="Title" type="text" class="form-control">
        <span asp-validation-for="Title" class="text-blackalert-danger"></span>
  </div>
    <div class="mb-3">
        <label asp-for="Author" class="form-label"><b>Author</b></label>
        <input asp-for="Author" type="text" class="form-control">
        <span asp-validation-for="Author" class="text-blackalert-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Description" class="form-label"><b>Description</b></label>
        <input asp-for="Description" type="text" class="form-control">
        <span asp-validation-for="Description" class="text-blackalert-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Genre" class="form-label"><b>Genre</b></label>
        <input asp-for="Genre" type="text" class="form-control">
        <span asp-validation-for="Genre" class="text-blackalert-danger"></span>
    </div>
@*     <div class="mb-3">
        <label asp-for="Genre" class="form-label"><b>Genre</b></label>
        <select asp-for="Genre" name="cars">
            <option value="Horror">Horror</option>
            <option value="Science Fiction">Science Fiction</option>
            <option value="Fantasy">Fantasy</option>
            <option value="Action">Action</option>
            <option value="Food & drink">Food & Drink</option>
        </select>
    </div> *@
  <div class="mb-3 form-check">
    <input asp-for="IsAvalible" type="checkbox" class="form-check-input">
        <label asp-for="IsAvalible" class="form-check-label"><b>IsAvalible</b></label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

BookUI/Views/Book/UpdateBook.cshtml
@model BookDTO

<h1>Update Book</h1>
<form asp-action="UpdateBook">
    <div class="mb-3">
        <label asp-for="Title" class="form-label"><b>Title</b></label>
        <input asp-for="Title" value=@Model.Title type="text" class="form-control">
        <span asp-validation-for="Title" class="text-blackalert-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Author" class="form-label"><b>Author</b></label>
        <input asp-for="Author" value=@Model.Author type="text" class="form-control">
        <span asp-validation-for="Author" class="text-blackalert-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Description" class="form-label"><b>Description</b></label>
        <input asp-for="Description" value=@Model.Description type="text" class="form-control">
        <span asp-validation-for="Description" class="text-blackalert-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Genre" class="form-label"><b>Genre</b></label>
        <input asp-for="Genre" value=@Model.Genre type="text" class="form-control">
        <span asp-validation-for="Genre" class="text-blackalert-danger"></span>
    </div>
    <div class="mb-3 form-check">
        <input asp-for="IsAvalible" type="checkbox" class="form-check-input">
        <label asp-for="IsAvalible" value=@Model.IsAvalible class="form-check-label"><b>IsAvalible</b></label>
    </div>
    <button type="submit" class="btn btn-primary">Update</button>
</form>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

BookUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BookUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookLibrary</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookUI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-black border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">BookLibrary</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Book" asp-action="BookIndex">Books</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BookUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>